Repository leo-vilelela/Quiz_JS, pull requests merged in 2023-07, with the labels that each got.

#12 Atualizacoes
  index.html
  style/style.css
Labels: enhancement

#13 Ranking
  static/ranking.html
Labels: enhancement

#15 Inserindo as questões do quiz
  script/cssQuestion.js
  script/htmlQuestion.js
  script/jsQuestion.js
Labels: enhancement

#16 Lógica principal
  index.html
  script/cssQuestion.js
  script/htmlQuestion.js
  script/jsQuestion.js
  script/script.js
  style/style.css
Labels: enhancement

#17 Removendo arquivos desnecessários
  static/quiz.html
  static/ranking.html
Labels: enhancement

#18 Correção do Botão iniciar
  script/script.js
Labels: enhancement

#20 estilizacao
  index.html
  script/cssQuestion.js
  script/htmlQuestion.js
  script/jsQuestion.js
  script/script.js
  style/style.css
Labels: enhancement

#23 alteracoes
  script/script.js
  style/style.css
Labels: enhancement

#24 teste
  index.html
  script/script.js
Labels: enhancement

#25 Refatorando Documento js e html
  index.html
  script/script.js
Labels: bug, enhancement

#28 Arrumando o bug do merge
  script/script.js
Labels: bug

#30 modificacoes
  script/script.js
Labels: enhancement

#31 Cronometro
  index.html
  script/script.js
  style/style.css
Labels: enhancement

#33 correcao cronometro
  index.html
Labels: enhancement

#34 Enhancements
  index.html
  script/script.js
  thinking-time-148496.mp3
Labels: enhancement

#36 alt
  index.html
  script/script.js
  style/style.css
Labels: enhancement

#39 Ajustes
  script/script.js
Labels: enhancement
