Repository leo-vilelela/Quiz_JS, pull requests merged in 2023-08, with the labels that each got.

#41 Adicionando tema a tabela
  script/script.js
Labels: enhancement

#43 botoes
  index.html
  script/cssQuestion.js
  script/script.js
  style/style.css
Labels: enhancement

#45 Criação De funções para pausar e coletar o tempo do cronômetro
  index.html
  script/script.js
Labels: bug, enhancement

#47 timeranking
  script/script.js
Labels: enhancement

#50 media
  index.html
  script/script.js
Labels: enhancement

#52 ranking
  .vscode/settings.json
  script/nomes.js
  script/script.js
Labels: enhancement

#54 estilizacaofinal
  script/script.js
  style/style.css
Labels: enhancement

#56 Arrumando o ranking
  script/nomesCSS.js
  script/nomesHtml.js
  script/nomesJS.js
  script/script.js
Labels: bug, enhancement

#57 Revert "Arrumando o ranking"
  script/nomes.js
  script/nomesCSS.js
  script/nomesJS.js
  script/script.js
Labels: bug, wontfix

#59 Arrumando links e ranking no js
  script/nomesCSS.js
  script/nomesHTML.js
  script/nomesJS.js
  script/script.js
Labels: bug, enhancement

#62 adicionando media de erros
  .vscode/settings.json
  script/nomesCSS.js
  script/nomesHTML.js
  script/nomesJS.js
  script/script.js
Labels: enhancement

#63 centralizando média
  script/script.js
  style/style.css
Labels: enhancement

#65 correção de variável duplicada
  script/script.js
  style/style.css
Labels: enhancement

#66 Audio
  script/script.js
Labels: bug, enhancement
